spring:
  application:
    name: rabbitmq-pustaka

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    template:
      exchange: peminjaman.exchange
    listener:
      simple:
        default-requeue-rejected: false

app:
  rabbitmq-peminjaman:
    queue: peminjaman.queue.email
    exchange: peminjaman.exchange
    routing-key: peminjaman.routing.key.email
  mail:
    host: "smtp.gmail.com"
    port: 587
    username: meilashinta26@gmail.com
    from: meilashinta26@gmail.com
    password: ygze bgyp sqnh kdpk
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  level:
    "[com.meila.rabbitmq-pustaka]": DEBUG

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8090
