apiVersion: v1
kind: Service
metadata:
  name: mongo-pustaka
spec:
  selector:
    app: mongo-pustaka
  ports:
    - port: 27017
      targetPort: 27017
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-pustaka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-pustaka
  template:
    metadata:
      labels:
        app: mongo-pustaka
    spec:
      containers:
        - name: mongo-pustaka
          image: mongo:latest
          ports:
            - containerPort: 27017
          livenessProbe:
            exec:
              command: ["mongosh", "--port", "27017", "--quiet", "--eval", "db.runCommand('ping').ok"]
            initialDelaySeconds: 30
            periodSeconds: 30