apiVersion: v1
kind: Service
metadata:
  name: buku-service
spec:
  selector:
    app: buku-service
  ports:
    - port: 8085
      targetPort: 8085
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: buku-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: buku-service
  template:
    metadata:
      labels:
        app: buku-service
    spec:
      containers:
        - name: buku-service
          # GANTI IMAGE
          image: furqonaugustseventeenth/buku-service:latest 
          ports:
            - containerPort: 8085
          env:
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://eureka-pustaka:8761/eureka/
            - name: SPRING_RABBITMQ_HOST
              value: rabbitmq-service
            - name: SPRING_RABBITMQ_PORT
              value: "5672"
            - name: SPRING_RABBITMQ_USERNAME
              value: admin
            - name: SPRING_RABBITMQ_PASSWORD
              value: password
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:h2:file:/app/data/buku;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE"
            - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
              value: org.h2.Driver
            - name: SPRING_DATASOURCE_USERNAME
              value: sa
            - name: SPRING_DATASOURCE_PASSWORD
              value: password
            - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
              value: "true"
            - name: EUREKA_INSTANCE_HOSTNAME
              value: "BUKU-SERVICE"
            - name: EUREKA_INSTANCE_INSTANCE_ID
              value: "BUKU-SERVICE:8005"
            - name: SERVER_PORT
              value: "8085"
            - name: LOGGING_FILE_NAME
              value: /app/logs/buku-service.log
          volumeMounts:
            - name: buku-data
              mountPath: /data
            - name: logs-volume
              mountPath: /app/logs
        # Sidecar
        - name: filebeat-buku
          # GANTI IMAGE
          image: furqonaugustseventeenth/filebeat:latest 
          command: ["filebeat", "-e", "--strict.perms=false"]
          volumeMounts:
            - name: logs-volume
              mountPath: /usr/share/filebeat/logs_input
              readOnly: true
      volumes:
        - name: buku-data
          persistentVolumeClaim:
            claimName: buku-data-pvc
        - name: logs-volume
          emptyDir: {}