apiVersion: v1
kind: Service
metadata:
  name: peminjaman-service
spec:
  selector:
    app: peminjaman-service
  ports:
    - port: 8086
      targetPort: 8086
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: peminjaman-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: peminjaman-service
  template:
    metadata:
      labels:
        app: peminjaman-service
    spec:
      containers:
        - name: peminjaman-service
          # GANTI IMAGE
          image: meilashinta/peminjaman-service:latest
          ports:
            - containerPort: 8086
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: docker
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://eureka-pustaka:8761/eureka/
            - name: SPRING_RABBITMQ_HOST
              value: rabbitmq-service
            - name: SPRING_RABBITMQ_PORT
              value: "5672"
            - name: SPRING_RABBITMQ_USERNAME
              value: admin
            - name: SPRING_RABBITMQ_PASSWORD
              value: password
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres-pustaka:5432/peminjaman
            - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
              value: org.postgresql.Driver
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: SPRING_DATASOURCE_PASSWORD
              value: postgres
            - name: SPRING_DATA_MONGODB_URI
              value: mongodb://mongo-pustaka:27017/peminjaman
            - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
              value: "true"
            - name: EUREKA_INSTANCE_HOSTNAME
              value: "PEMINJAMAN-SERVICE"
            - name: EUREKA_INSTANCE_INSTANCE_ID
              value: "PEMINJAMAN-SERVICE:8006"
            - name: SPRING_APPLICATION_NAME
              value: "peminjaman-service"
            - name: SERVER_PORT
              value: "8086"
            - name: LOGGING_FILE_NAME
              value: /app/logs/peminjaman-service.log
          volumeMounts:
            - name: peminjaman-data
              mountPath: /data
            - name: logs-volume
              mountPath: /app/logs
        # Sidecar
        - name: filebeat-peminjaman
          # GANTI IMAGE
          image: meilashinta/filebeat:latest
          command: ["filebeat", "-e", "--strict.perms=false"]
          volumeMounts:
            - name: logs-volume
              mountPath: /usr/share/filebeat/logs_input
              readOnly: true
      volumes:
        - name: peminjaman-data
          persistentVolumeClaim:
            claimName: peminjaman-data-pvc
        - name: logs-volume
          emptyDir: {}
