apiVersion: v1
kind: Service
metadata:
  name: api-gateway-pustaka
spec:
  selector:
    app: api-gateway-pustaka
  type: LoadBalancer 
  ports:
    - port: 9002
      targetPort: 9002
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-pustaka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway-pustaka
  template:
    metadata:
      labels:
        app: api-gateway-pustaka
    spec:
      containers:
        - name: api-gateway-pustaka
          # GANTI IMAGE
          image: furqonaugustseventeenth/api-gateway-pustaka:latest 
          ports:
            - containerPort: 9002
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: docker
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://eureka-pustaka:8761/eureka/
            - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
              value: "true"
            - name: EUREKA_INSTANCE_HOSTNAME
              value: "API-GATEWAY-PUSTAKA"
            - name: EUREKA_INSTANCE_INSTANCE_ID
              value: "API-GATEWAY-PUSTAKA:9002"
            - name: SERVER_PORT
              value: "9002"
            - name: LOGGING_FILE_NAME
              value: /app/logs/gateway-service.log
          volumeMounts:
            - name: logs-volume
              mountPath: /app/logs
        # Sidecar
        - name: filebeat-gateway
          # GANTI IMAGE
          image: furqonaugustseventeenth/filebeat:latest 
          command: ["filebeat", "-e", "--strict.perms=false"]
          volumeMounts:
            - name: logs-volume
              mountPath: /usr/share/filebeat/logs_input
              readOnly: true
      volumes:
        - name: logs-volume
          emptyDir: {}