apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-email-service
  labels:
    app: rabbitmq-email-service
    monitoring: enabled
spec:
  selector:
    app: rabbitmq-email-service
  ports:
    - name: http
      port: 8090
      targetPort: 8090
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-email-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq-email-service
  template:
    metadata:
      labels:
        app: rabbitmq-email-service
    spec:
      containers:
        - name: rabbitmq-email-service
          image: meilashinta/rabbitmq-email-service:latest
          ports:
            - containerPort: 8090

          env:
            - name: SPRING_PROFILES_ACTIVE
              value: docker
            - name: SPRING_APPLICATION_NAME
              value: rabbitmq-email-service
            - name: SERVER_PORT
              value: "8090"

            # RabbitMQ Broker
            - name: SPRING_RABBITMQ_HOST
              value: rabbitmq-service
            - name: SPRING_RABBITMQ_PORT
              value: "5672"
            - name: SPRING_RABBITMQ_USERNAME
              value: admin
            - name: SPRING_RABBITMQ_PASSWORD
              value: password

            - name: SPRING_RABBITMQ_TEMPLATE_EXCHANGE
              value: peminjaman.exchange
            - name: SPRING_RABBITMQ_LISTENER_SIMPLE_DEFAULT_REQUEUE_REJECTED
              value: "false"

            # App config
            - name: APP_RABBITMQ_PEMINJAMAN_QUEUE
              value: peminjaman.queue.email
            - name: APP_RABBITMQ_PEMINJAMAN_ROUTING_KEY
              value: peminjaman.routing.key.email

            # Mail
            - name: APP_MAIL_HOST
              value: smtp.gmail.com
            - name: APP_MAIL_PORT
              value: "587"
            - name: APP_MAIL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: smtp-secret
                  key: SMTP_USERNAME
            - name: APP_MAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: smtp-secret
                  key: SMTP_PASSWORD
            - name: APP_MAIL_FROM
              valueFrom:
                secretKeyRef:
                  name: smtp-secret
                  key: SMTP_FROM

            - name: APP_MAIL_PROPERTIES_MAIL_SMTP_AUTH
              value: "true"
            - name: APP_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE
              value: "true"

            # Eureka
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://eureka-pustaka:8761/eureka/
            - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
              value: "true"
            - name: EUREKA_INSTANCE_HOSTNAME
              value: "RABBITMQ-email-SERVICE"
            - name: EUREKA_INSTANCE_INSTANCE_ID
              value: "RABBITMQ-email-SERVICE:8090"

            # Logging (PENTING UNTUK FILEBEAT)
            - name: LOGGING_FILE_NAME
              value: /app/logs/rabbitmq-email-service.log
            - name: LOGGING_LEVEL_ROOT
              value: INFO

            - name: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
              value: "health,info,prometheus"
            - name: MANAGEMENT_METRICS_TAGS_APPLICATION
              value: "rabbitmq-email-service"

          volumeMounts:
            - name: logs-volume
              mountPath: /app/logs

        # Sidecar Filebeat
        - name: filebeat-rabbitmq-email
          image: meilashinta/filebeat:latest
          command: ["filebeat", "-e", "--strict.perms=false"]
          securityContext:
            runAsUser: 0
          volumeMounts:
            - name: logs-volume
              mountPath: /usr/share/filebeat/logs_input
              readOnly: true

      volumes:
        - name: logs-volume
          emptyDir: {}